// <auto-generated />
using System;
using Accommodation.Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Accommodation.Database.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260831093522_AddSearchHistory")]
    partial class AddSearchHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("Accommodation.Database.Data.Accommodation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AmenitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("amenities");

                    b.Property<string>("BookingUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("booking_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("destination")
                        .UseCollation("NOCASE");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_guests");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<long>("NightlyPrice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("nightly_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Destination", "IsActive");

                    b.HasIndex("Name", "Destination")
                        .IsUnique();

                    b.ToTable("accommodations", null, t =>
                        {
                            t.HasCheckConstraint("CK_accommodations_amenities_json", "json_valid(amenities) AND json_type(amenities) = 'array'");

                            t.HasCheckConstraint("CK_accommodations_max_guests", "max_guests >= 1 AND max_guests <= 20");

                            t.HasCheckConstraint("CK_accommodations_nightly_price", "nightly_price >= 0 AND nightly_price <= 10000000");
                        });
                });

            modelBuilder.Entity("Accommodation.Database.Data.Search", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateOnly>("CheckIn")
                        .HasColumnType("TEXT")
                        .HasColumnName("check_in");

                    b.Property<DateOnly>("CheckOut")
                        .HasColumnType("TEXT")
                        .HasColumnName("check_out");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("destination")
                        .UseCollation("NOCASE");

                    b.Property<int>("Guests")
                        .HasColumnType("INTEGER")
                        .HasColumnName("guests");

                    b.Property<long>("MaximumPrice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_price");

                    b.Property<long>("MinimumPrice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_price");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("preferences");

                    b.Property<string>("RankingMode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("ranking_mode");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("results_json");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("searches", null, t =>
                        {
                            t.HasCheckConstraint("CK_searches_dates", "check_out > check_in");

                            t.HasCheckConstraint("CK_searches_guests", "guests >= 1 AND guests <= 20");

                            t.HasCheckConstraint("CK_searches_prices", "min_price >= 0 AND max_price <= 10000000 AND min_price <= max_price");

                            t.HasCheckConstraint("CK_searches_ranking_mode", "ranking_mode IN ('ai', 'fallback')");

                            t.HasCheckConstraint("CK_searches_results_json", "json_valid(results_json) AND json_type(results_json) = 'array'");

                            t.HasCheckConstraint("CK_searches_text_lengths", "length(trim(title)) BETWEEN 1 AND 80 AND length(trim(destination)) BETWEEN 2 AND 100 AND length(preferences) <= 500");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
