// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Accommodation.Database.Data;

#nullable disable

namespace Accommodation.Database.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("Accommodation.Database.Data.Accommodation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AmenitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("amenities");

                    b.Property<string>("BookingUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("booking_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("destination")
                        .UseCollation("NOCASE");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_guests");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<long>("NightlyPrice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("nightly_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Destination", "IsActive");

                    b.HasIndex("Name", "Destination")
                        .IsUnique();

                    b.ToTable("accommodations", null, t =>
                        {
                            t.HasCheckConstraint("CK_accommodations_amenities_json", "json_valid(amenities) AND json_type(amenities) = 'array'");

                            t.HasCheckConstraint("CK_accommodations_max_guests", "max_guests >= 1 AND max_guests <= 20");

                            t.HasCheckConstraint("CK_accommodations_nightly_price", "nightly_price >= 0 AND nightly_price <= 10000000");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
